config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :cases
      resources :links
      resources :people
      resources :professions

      root to: "users#index"
    end
  root 'pages#index'

  devise_for :users

  resources :persons
  resources :cases

  get 'o-projekte' => 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  has_and_belongs_to_many :links
  has_and_belongs_to_many :people

  validates :name, :presence => true, :uniqueness => true
  paginates_per 26

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/link.rb
class Link < ApplicationRecord
  has_and_belongs_to_many :cases

  validates :title, :url, :presence => true
end

app/models/person.rb
class Person < ApplicationRecord
  has_person_name
  has_one :profession
  has_and_belongs_to_many :cases

  validates :first_name, :last_name, :presence => true
  paginates_per 26

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/profession.rb
class Profession < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    # before_action :authenticate_admin
    before_action :authenticate_user!

    # def authenticate_admin
    #   # TODO Add authentication logic here.
    # end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/cases_controller.rb
module Admin
  class CasesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Case.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Case.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/links_controller.rb
module Admin
  class LinksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Link.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Link.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/people_controller.rb
module Admin
  class PeopleController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Person.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Person.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/professions_controller.rb
module Admin
  class ProfessionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Profession.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Profession.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController

  def index
    @cases = Case.order(:name).page params[:page]
  end

  def show
    @case = Case.friendly.find(params[:id])
    @associated_persons = @case.people
    @associated_links = @case.links
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  def index
    @persons = Person.all.page params[:page]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cases/index.html.erb
<h1 class="font-sans break-normal text-gray-900 font-bold text-xl">Kauzy (<%= @cases.total_count %>)</h1>
<small>Toto sú kauzy, ktoré momentálne evidujeme v našej databáze.</small>

<% @cases.each do |c| %>

  <div class="rounded border border-gray-400 bg-white mt-4 mb-2 p-6">
    <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl"><%= c.name %></h2>
    <p><%= c.description %></p>
    <%= link_to 'Zistiť viac', case_path(c), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 inline-block rounded" %>
  </div>

<% end %>

<%= paginate @cases %>

app/views/cases/show.html.erb
<h1 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl"><%= @case.name %></h1>
<p><%= @case.description %></p>

<h2 class="font-sans break-normal text-gray-900 pb-2 mt-6 font-bold text-l">
  Ľudia spájaní s touto kauzou
  <% if @associated_persons.present? %>
    (<%= @associated_persons.count %>)
  <% end %>
</h2>
<% if @associated_persons.empty? %>
  <p>S touto kauzou zatiaľ neboli spojené žiadne osoby.</p>
<% else %>
  <div class="flex mb-4 overflow-auto">
    <% @associated_persons.each do |person| %>

      <%= link_to person_path(person), title: person.name.full do %>
        <div class="rounded border border-gray-400 hover:shadow-lg shadow-none bg-white mt-2 mb-2 mr-3 w-32 truncate">
          <div style="background-image: url('<%= person.img_url %>')" class="bg-cover h-32"></div>
          <p class="block p-2"><%= person.name.truncate(13) %></p>
        </div>
      <% end %>

    <% end %>
  </div>
<% end %>

<h2 class="font-sans break-normal text-gray-900 pb-2 mt-6 font-bold text-l">
  Prečítajte si viac <% if @associated_links.present? %>(<%= @associated_links.count %>)<% end %>
</h2>
<% if @associated_links.empty? %>
  <p>K tejto kauze zatiaľ neboli pridané žiadne odkazy.</p>
<% else %>
  <% @associated_links.in_groups_of(2, false).each do |group| %>
    <div class="mb-4 flex">
      <% group.each do |link| %>
        <div class="w-2/4 p-1">
          <%= link_to link.url, title: link.title, target: :_blank do %>

            <div class="rounded border flex border-gray-400 mt-2 mb-2 shadow-none hover:shadow-lg">
              <% if link.img_url.present? %>
                <div class="bg-cover w-1/6 hidden sm:block" style="background-image: url('<%= link.img_url %>')"></div>
              <% else %>
                <div class="bg-cover w-1/6 hidden sm:block" style="background-image: url('https://via.placeholder.com/128')"></div>
              <% end %>
              <div class="pr-2 pt-2 pb-2 pl-2 w-5/6">
              <h3 class="font-sans break-normal text-gray-900 font-bold text-xl">
                <%= link.title.truncate(35) %>
              </h3>
              <small class="block text-gray-500 overflow-hidden"><%= link.url.truncate(40) %></small>
              </div>
            </div>

          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-white border-t border-gray-400 shadow">
  <div class="container mx-auto flex py-8">
    <div class="w-full mx-auto flex flex-wrap">
      <div class="flex w-full lg:w-1/3">
        <div class="px-8">
          <h3 class="font-bold text-gray-900"><%= link_to 'Politici', persons_url %></h3>
          <ul class="list-reset items-center text-sm pt-3">
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Róbert Fico</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Andrej Kiska</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Ivan Štefunko</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Róbert Fico</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Andrej Kiska</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Ivan Štefunko</a></li>
          </ul>
        </div>
      </div>
      <div class="flex w-full lg:w-1/3">
        <div class="px-8">
          <h3 class="font-bold text-gray-900"><%= link_to 'Kauzy', cases_url %></h3>
          <ul class="list-reset items-center text-sm pt-3">
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Sasánka</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Pozemky pod Tatrami</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Náklady na kampaň</a></li>
            <li><a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Predražené CT</a></li>
          </ul>
        </div>
      </div>
      <div class="flex w-full lg:w-1/3 lg:justify-end">
        <div class="px-8">
          <h3 class="font-bold text-gray-900">Buďte informovaný o novinkách</h3>
          <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
              <p class="text-gray-600 text-sm py-2">Veľmi občas Vám môžem napísať, ako sa tento projekt vyvíja.</p>
              <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 mt-2" for="grid-password">
                E-mailová adresa
              </label>
              <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-password" type="email" placeholder="zaujimamsao@slovensko.sk">
              <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
                Prihlásiť sa
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container mx-auto flex py-8 border-t">
    <p class="w-full text-center text-sm">
      <%= link_to 'O projekte', o_projekte_url, class: "text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" %> &middot;
      <%= link_to 'O autorovi', root_path, class: "text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" %> &middot;
      <%= link_to 'Ochrana súkromia', root_path, class: "text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" %> &middot;
      <%= link_to 'Podmienky používania', root_path, class: "text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" %>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav id="header" class="fixed w-full z-10 top-0 bg-white border-b border-gray-400">
  <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-4">
    <div class="pl-4 flex items-center">
      <svg class="h-5 pr-3 fill-current text-purple-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <path d="M0 2C0 .9.9 0 2 0h16a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm14 12h4V2H2v12h4c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2zM5 9l2-2 2 2 4-4 2 2-6 6-4-4z"/>
      </svg>
      <%= link_to "Kauzy", root_url, class: "text-gray-900 text-base no-underline hover:no-underline font-bold text-xl" %>
    </div>
    <div class="block lg:hidden pr-4">
      <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-purple-500 appearance-none focus:outline-none">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>
    <div class="w-full flex-grow lg:flex  lg:content-center lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 z-20" id="nav-content">
      <div class="flex-1 w-full mx-auto max-w-sm content-center py-4 lg:py-0">
        <div class="relative pull-right pl-4 pr-4 md:pr-0">
          <input type="search" placeholder="Vyhľadávanie" class="w-full bg-gray-100 text-sm text-gray-800 transition border focus:outline-none focus:border-purple-500 rounded py-1 px-2 pl-10 appearance-none leading-normal">
          <div class="absolute search-icon" style="top: 0.375rem;left: 1.75rem;">
            <svg class="fill-current pointer-events-none text-gray-800 w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
              <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
            </svg>
          </div>
        </div>
      </div>
      <ul class="list-reset lg:flex justify-end items-center">
        <li class="mr-3 py-2 lg:py-0">
          <%= link_to 'Kauzy', cases_path, class: "inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-2 px-4" %>
        </li>
        <li class="mr-3 py-2 lg:py-0">
          <%= link_to 'Politici', persons_path, class: "inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-2 px-4" %>
        </li>
        <li class="mr-3 py-2 lg:py-0">
          <%= link_to 'O projekte', o_projekte_path, class: "inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-2 px-4" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Kauzy</title>

    <meta name="description" content="">
    <meta name="keywords" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-100 tracking-wider tracking-normal">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'layouts/header' %>

    <div class="container w-full flex flex-wrap mx-auto px-2 pt-8 lg:pt-16 mt-8">
      <div class="w-full p-8 mt-2 mb-6 text-gray-900 leading-normal bg-white border border-gray-400 border-rounded">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-4xl">O projekte</h1>

<p class="mt-5">Pár mesiacov dozadu som sa začal zaujímať o prípady, s ktorými bol spojený jeden nemenovaný politik. Čím viac som však hľadal informácie, tým viac som sa cítil stratený a preto som sa rozhodol prísť s týmto projektom. Každý by si mal byť schopný nájsť veréjne známu osobnosť a pozrieť sa s akými kauzami je spájaná.</p>

<!-- TODO: Write about the validity of the information provided -->

<p class="mt-8">Tento projekt je open source - čo znamená, že zdrojové súbory tejto aplikácie sú veréjne dostupné a každá pomoc je vítaná.</p>

app/views/pages/index.html.erb
<div class="flex mb-4">
  <div class="w-1/2 pr-2">
    <h2>Najkontroverznejší politici</h2>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="Robert Fico" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>Robert Fico</h3>
        <span>Spajaný so 40 kauzami.</span>
      </div>
    </div>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="Andrej Danko" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>Andrej Danko</h3>
        <span>Spajaný so 30 kauzami.</span>
      </div>
    </div>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="Robert Kalinak" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>Robert Kalinak</h3>
        <span>Spajaný so 20 kauzami.</span>
      </div>
    </div>
  </div>

  <div class="w-1/2 pl-2">
    <h2>Najkontroverznejšie politické strany</h2>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="SMER" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>SMER</h3>
        <span>Spajaný so 50 kauzami.</span>
      </div>
    </div>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="SMER" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>SNS</h3>
        <span>Spajaný so 40 kauzami.</span>
      </div>
    </div>
    <div class="bg-white shadow-md border flex rounded px-4 pt-3 pb-4 mb-4">
      <img src="https://via.placeholder.com/128" alt="SMER" class="h-16 w-16 rounded-full object-cover">
      <div class="flex-auto ml-2">
        <h3>Most-HID</h3>
        <span>Spajaný so 30 kauzami.</span>
      </div>
    </div>
  </div>
</div>

<p>Táto databáza sa neustále rozširuje a tak je nemožné, aby štatistiky uvedené vyššie zodpovedali absolútne realite.</p>

app/views/persons/index.html.erb
<h1 class="font-sans break-normal text-gray-900 font-bold text-xl">Politici (<%= @persons.total_count %>)</h1>
<small>Toto sú veréjne osobnosti, ktoré momentálne evidujeme v našej databáze.</small>

<% @persons.in_groups_of(2, false).each do |group| %>

  <div class="flex">
    <% group.each do |person| %>
      <div class="w-1/2 rounded border border-gray-400 shadow-lg bg-white mt-4 mb-2 m-3 inline-block">
        <div class="flex">
          <div class="w-1/3">
            <img src="<%= person.img_url %>" alt="<%= person.name %>" width="170">
          </div>
          <div class="w-2/3 p-6">
            <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl"><%= person.name %></h2>
            <p>politik</p>
            <%= link_to 'Zobraziť profil', person_path(person), class: "bg-blue-500 inline-block hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

<%= paginate @persons %>

app/views/persons/show.html.erb
<div class="flex mb-4">
  <div class="w-1/3">

    <img src="http://www.nrsr.sk/web/dynamic/PoslanecPhoto.aspx?PoslanecID=40&amp;ImageWidth=128" alt="Robert Fico" height="128" width="128">
    <h1 class="font-sans break-normal text-gray-900 pt-6 pb-2 text-xl">Róbert Fico (54)</h1>
    <p>politik, poslanec SMER-SD</p>

    <div class="mt-6 w-2/3 text-gray-600 text-xs">
      <p class="mt-4">V roku 1987 vstúpil do Komunistickej strany Slovenska a po revolúcii sa stal členom Strany demokratickej ľavice (SDĽ), za ktorú bol v roku 1992 zvolený za poslanca Národnej rady SR.</p>
      <p class="mt-4">SDĽ bola v roku 1998 súčasťou vládnej koalície spolu so Slovenskou demokratickou koalíciou (SDK), Stranou maďarskej koalície (SMK) a Stranou občianskeho porozumenia (SOP), no Robert Fico sa pre nesúhlas a sklamanie z obsahu a štýlu politiky, ktorú realizovala „vláda zmeny“, rozhodol v auguste 1999 SDĽ opustiť a v NR SR bol nezávislým poslancom.</p>
    </div>

  </div>
  <div class="w-2/3">

    <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl">Kauzy s ním spájané (12)</h2>

    <div class="rounded border border-gray-400 bg-white mt-2 mb-2 p-6">
      <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl">Gorila</h2>
      <p>Prevalila sa uniknutím tajného dokumentu s krycím názvom Gorila zo Slovenskej informačnej služby na verejnosť v decembri 2011. V spise zverejnenom na internete sa nachádzajú informácie o odpočúvaní Jaroslava Haščáka, šéfa investičnej skupiny Penta, počas rokov 2005 a 2006...</p>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded">
        Zistiť viac
      </button>
    </div>

    <div class="rounded border border-gray-400 bg-white mt-2 mb-2 p-6">
      <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl">Predražené CT v Piešťanoch</h2>
      <p>Prevalila sa uniknutím tajného dokumentu s krycím názvom Gorila zo Slovenskej informačnej služby na verejnosť v decembri 2011. V spise zverejnenom na internete sa nachádzajú informácie o odpočúvaní Jaroslava Haščáka, šéfa investičnej skupiny Penta, počas rokov 2005 a 2006...</p>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded">
        Zistiť viac
      </button>
    </div>

    <div class="rounded border border-gray-400 bg-white mt-2 mb-2 p-6">
      <h2 class="font-sans break-normal text-gray-900 pb-2 font-bold text-xl">Baštrnák</h2>
      <p>Prevalila sa uniknutím tajného dokumentu s krycím názvom Gorila zo Slovenskej informačnej služby na verejnosť v decembri 2011. V spise zverejnenom na internete sa nachádzajú informácie o odpočúvaní Jaroslava Haščáka, šéfa investičnej skupiny Penta, počas rokov 2005 a 2006...</p>
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded">
        Zistiť viac
      </button>
    </div>

  </div>
</div>